# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, closed, reopened]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Auto Create Tag on Pull-Request Merged test you  
      run: |
        echo "The event_name is: ${{ github.event_name }}"
        echo "The event.pull_request.merged is: ${{ github.event.pull_request.merged }}"
        echo "The event action is: ${{ github.event.action }}"      

    - name: Gitversion Install
      run: dotnet tool install --global GitVersion.Tool --version 5.*
      continue-on-error: true

    - name: Gitversion Determine Version
      run: dotnet-gitversion /output json /output buildserver /config GitVersion.yml /updateprojectfiles

    - name: Auto Create Tag on Pull-Request Merged
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.action == 'closed'
      run: |
        git tag 0.1.0 
        git push orgin 0.1.0 
